
frsRandomREG    = RNG_DAT_LO

frsRandomByte   .macro
                lda frsRandomREG
                .endmacro

frsRandomByteX  .macro
                ldx frsRandomREG
                .endmacro

frsRandomByteY  .macro
                ldy frsRandomREG
                .endmacro

frsRandomWord   .macro
                ; lda frsRandomREG
                .endmacro

frsRandomClamp  .macro clamp
                ; TODO:
                .endmacro
